### ISSUE TITLE
`time` 0.2.23 does not compile on rust 1.48.0

### ISSUE THREAD

**Issue by samuela** [time-rs/time#300]
`time` is used as some transitive dependency of `cookie`, which I'm trying to use. I just added `cookie = "0.14"` to my Cargo.toml, but `time` is refusing to compile:
```
error[E0624]: associated function `to_mmp` is private
  --> /Users/skainswo/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:30:69
   |
30 |         Some((version, channel, _)) if channel.is_dev() => (version.to_mmp().1 - 2, channel),
   |                                                                     ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/skainswo/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:31:73
   |
31 |         Some((version, channel, _)) if channel.is_nightly() => (version.to_mmp().1 - 1, channel),
   |                                                                         ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/skainswo/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs:32:49
   |
32 |         Some((version, channel, _)) => (version.to_mmp().1, channel),
   |                                                 ^^^^^^ private associated function

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0624`.
error: could not compile `time`

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build --edition=2018 /Users/skainswo/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.23/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="stdweb"' --cfg 'feature="winapi"' -C metadata=82bc1305b5954f01 -C extra-filename=-82bc1305b5954f01 --out-dir /Users/skainswo/dev/cuddlefish/api/target/debug/build/time-82bc1305b5954f01 -L dependency=/Users/skainswo/dev/cuddlefish/api/target/debug/deps --extern version_check=/Users/skainswo/dev/cuddlefish/api/target/debug/deps/libversion_check-e928c312abc4f45f.rlib --cap-lints allow` (exit code: 1)
```
I'm using
```
❯ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```
on macOS 10.15.4. Happy to provide any other diagnostics that may be helpful!

**Comment by samuela** [comment]
I just cloned master (at ec4057d6b8606ec7485380328cf3baedc9b60e54) and it builds fine for me.

**Comment by jhpratt** [comment]
Please search before opening an issue; this is identical to #295.
