### ISSUE TITLE
Possible regression in `time::convert::Nanoseconds`

### ISSUE THREAD

**Issue by coryan** [time-rs/time#749]
This works with 0.3.41:

```rust
#[test]
fn convert() {
    use time::convert::{Nanosecond, Second};
    let convert = Nanosecond::per(Second);
    assert_eq!(convert, 1_000_000_000);
}
```

it fails for me with 0.3.42:

```
cargo test
   Compiling time-rs-regression v0.1.0 (/Users/coryan/time-rs-regression)
error[E0277]: the trait bound `Second: time::convert::sealed::DefaultOutput<Nanosecond>` is not satisfied
   --> src/main.rs:5:35
    |
5   |     let convert = Nanosecond::per(Second);
    |                   --------------- ^^^^^^ the trait `time::convert::sealed::DefaultOutput<Nanosecond>` is not implemented for `Second`
    |                   |
    |                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `time::convert::sealed::DefaultOutput<T>`:
              `Second` implements `time::convert::sealed::DefaultOutput<Day>`
              `Second` implements `time::convert::sealed::DefaultOutput<Hour>`
              `Second` implements `time::convert::sealed::DefaultOutput<Minute>`
              `Second` implements `time::convert::sealed::DefaultOutput<Second>`
              `Second` implements `time::convert::sealed::DefaultOutput<Week>`
note: required by a bound in `Nanosecond::per`
   --> /Users/coryan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/time-core-0.1.5/src/convert.rs:109:1
    |
109 | / impl_per! {
110 | |     Nanosecond ("nanosecond") per {
111 | |         Nanosecond: [u8] u8|u16|u32|u64|u128|usize|i8|i16|i32|i64|i128|isize = 1; f32|f64 = 1.;
112 | |         Microsecond: [u16] u16|u32|u64|u128|usize|i16|i32|i64|i128|isize = 1_000; f32|f64 = 1_000.;
...   |
163 | | }
    | | ^
    | | |
    | |_required by a bound in this associated function
    |   required by this bound in `Nanosecond::per`
    = note: this error originates in the macro `impl_per` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Second: time::convert::sealed::DefaultOutput<Nanosecond>` is not satisfied
 --> src/main.rs:5:19
  |
5 |     let convert = Nanosecond::per(Second);
  |                   ^^^^^^^^^^^^^^^^^^^^^^^ the trait `time::convert::sealed::DefaultOutput<Nanosecond>` is not implemented for `Second`
  |
  = help: the following other types implement trait `time::convert::sealed::DefaultOutput<T>`:
            `Second` implements `time::convert::sealed::DefaultOutput<Day>`
            `Second` implements `time::convert::sealed::DefaultOutput<Hour>`
            `Second` implements `time::convert::sealed::DefaultOutput<Minute>`
            `Second` implements `time::convert::sealed::DefaultOutput<Second>`
            `Second` implements `time::convert::sealed::DefaultOutput<Week>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `time-rs-regression` (bin "time-rs-regression" test) due to 2 previous errors
```

```
cargo version
cargo 1.89.0 (c24e10642 2025-06-23)
```

**Comment by jhpratt** [comment]
Released.
